clc; clear all;
mexCPU(1, 'getfeg.cpp', 'D:/MULTEM/General_CPU_GPU', 'hQuadrature.cpp', 'hAtomicdata.cpp'...
    , 'hPotential_CPU.cpp', 'hMT_General_CPU.cpp', 'hMT_AtomTypes_CPU.cpp', 'hfeg_CPU.cpp');