clc; clear all;
MEX(1, 'get_feg_CPU.cpp', '../General_CPU_GPU', ...
       'hQuadrature.cpp', ...
       'hMT_AtomicData_CPU.cpp', ...
       'hPotential_CPU.cpp', ...
       'hGeneral_CPU.cpp', ...
       'hMT_General_CPU.cpp', ...
       'hMT_AtomTypes_CPU.cpp', ...
       'hfeg_CPU.cpp');