mexCPU(0, 'MULTEM_CPU.cpp', '../General_CPU_GPU', ...
       'hQuadrature.cpp', ...
       'hMT_AtomicData_CPU.cpp', ...
       'hPotential_CPU.cpp', ...
       'hGeneral_CPU.cpp', ...
       'hMT_Slicing_CPU.cpp', ...
       'hMT_Specimen_CPU.cpp', ...
       'hMT_AtomTypes_CPU.cpp', ...
       'hMT_General_CPU.cpp', ...
       'hMT_Detector_CPU.cpp', ...
       'hMT_Potential_CPU.cpp', ...
       'hMT_Transmission_CPU.cpp', ...
       'hMT_IncidentWave_CPU.cpp', ...
       'hMT_MicroscopeEffects_CPU.cpp', ...
       'hMT_STEM_CPU.cpp', ...
       'hMT_MulSli_CPU.cpp');
