addpath([ pwd '/Matlab_functions'])

files = {'mex_radial_distribution_2D', ...
        'mex_filter_Butterworth', ...
        'mex_filter_Gaussian', ...
        'mex_filter_Hanning', ...
        'mex_convolution_gaussian',...
        'mex_poisson_noise',...
        'mex_sigma',...
        'mex_FFT_information_limit_2D', ...
        'mex_cubic_spline',...
        'mex_otsu_threshold',...
        'mex_binary',... 
        'mex_scale_image',...
        'mex_morf_dilation',...        
        'mex_extract_shape',...
        'mex_fxeg_tabulated_data', ...
        'mex_quadrature', ...
        'mex_feg', ...
        'mex_fxg', ...
        'mex_Pr', ...
        'mex_Vz', ...
        'mex_Vr', ...
        'mex_Vp', ...
        'mex_atom_radius', ...
        'mex_atom_type', ...
        'mex_crystal_by_layers', ...
        'mex_specimen_slicing', ...
        'mex_incident_wave', ...
        'mex_propagate', ...
        'mex_microscope_aberrations', ...
        'mex_projected_potential', ...
        'mex_transmission_function', ... 
        'mex_wave_function', ...
        'mex_MULTEM', ...
        'mex_cross_section'};
for file=files
  disp(['Compiling ' file{1}])
  run(['mex_files/', file{1}])
end;