% Copyright 2021 Ivan Lobato <Ivanlh20@gmail.com>
clear;clc;

addpath([ pwd '/matlab_functions'])

files = {
        'mex_spec_rot', ...
        'mex_spec_planes', ...
        'mex_spec_slicing', ...
        'mex_incident_wave', ...
        'mex_propagate', ...
        'mex_microscope_aberrations', ...
        'mex_projected_potential', ...
        'mex_transmission_function', ...
        'mex_wave_function', ...
        'mex_multem'};

for file=files
  disp(['Compiling ' file{1}])
  run(['mex_files_multem/', file{1}])
end

% % Copyright 2021 Ivan Lobato <Ivanlh20@gmail.com>
% clear;clc;
% 
% addpath([ pwd '/matlab_functions'])
% 
% files = {'mex_lambda', ...
%         'mex_gamma', ...
%         'mex_e_interact_parm', ...
%         'mex_transf_exp_factor', ...
%         'mex_rangs_2_mrad', ...
%         'mex_mrad_2_rangs', ...
%         'mex_mrad_2_sigma', ...
%         'mex_fwhm_2_sigma', ...
%         'mex_hwhm_2_sigma', ...
%         'mex_iehwgd_2_sigma', ...
%         'mex_scherzer_defocus', ...
%         'mex_scherzer_aperture', ...
%         'mex_g_max', ...
%         'mex_det_min_spl', ...
%         'mex_rdf', ...  
%         'mex_min_dist', ... 
%         'mex_max_dist', ... 
%         'mex_atomic_radius', ...
%         'mex_atomic_info', ...
%         'mex_feg', ...
%         'mex_fxg', ...
%         'mex_pr', ...
%         'mex_vz', ...
%         'mex_vr', ...
%         'mex_vzp', ...
%         'mex_fxeg_data', ...
%         'mex_xtl_csn_2_sgr', ...
%         'mex_xtl_css_2_csn', ...
%         'mex_xtl_css_2_sgr', ...
%         'mex_xtl_sgn_2_csn', ...
%         'mex_xtl_build_base', ...
%         'mex_xtl_build', ...
%         'mex_amorp_build', ...
%         'mex_amorp_lay_add', ...
%         'mex_spec_rot', ...
%         'mex_spec_planes', ...
%         'mex_spec_slicing', ...
%         'mex_incident_wave', ...
%         'mex_propagate', ...
%         'mex_microscope_aberrations', ...
%         'mex_projected_potential', ...
%         'mex_transmission_function', ...
%         'mex_wave_function', ...
%         'mex_multem'};
% 
% for file=files
%   disp(['Compiling ' file{1}])
%   run(['mex_files_multem/', file{1}])
% end