addpath([ pwd '/Matlab_functions'])

files = {'mex_crystal_by_layers',...
        'mex_specimen_slicing',...
        'mex_incident_wave',...
        'mex_propagate',...
        'mex_microscope_aberrations',...
        'mex_projected_potential',...
        'mex_transmission_function',... 
        'mex_wave_function',...
        'mex_MULTEM'};
for file=files
  disp(['Compiling ' file{1}])
  run(['mex_files/',file{1}])
end;