mexGPU(0, 'getPropagate.cu', '../General_CPU_GPU', ...
       'hGeneral_CPU.cpp', ...
       'hQuadrature.cpp', ...
       'hMT_AtomicData_CPU.cpp', ...
       'hPotential_CPU.cpp', ...
       'hMT_General_CPU.cpp', ...
       'hMT_General_GPU.cu');
