clc; clear all;
MEX(1, 'get_Identify_Planes_CPU.cpp', '../General_CPU_GPU', ...
       'hQuadrature.cpp', ...
       'hGeneral_CPU.cpp', ...
       'hMT_AtomicData_CPU.cpp', ...
       'hPotential_CPU.cpp', ...
       'hMT_General_CPU.cpp', ...
       'hMT_AtomTypes_CPU.cpp', ...
       'hMT_Slicing_CPU.cpp', ...
       'hMT_Specimen_CPU.cpp');
