clc; clear all;
mexGPU(1, 'getProbe.cu', '../General_CPU_GPU', 'hQuadrature.cpp', 'hAtomicData.cpp'...
    , 'hPotential_CPU.cpp', 'hMT_General_CPU.cpp', 'hMT_General_GPU.cu', 'hMT_IncidentWave_GPU.cu');