MEX(0, 'get_PCBFTEM_GPU.cu', '../General_CPU_GPU', ...
       'hGeneral_CPU.cpp', ...
       'hQuadrature.cpp', ...
       'hMT_AtomicData_CPU.cpp', ...
       'hMT_AtomTypes_CPU.cpp', ...
       'hPotential_CPU.cpp', ...
       'hMT_General_CPU.cpp', ...
       'hMT_Specimen_CPU.cpp', ...
       'hMT_General_GPU.cu', ...
       'hMT_MicroscopeEffects_GPU.cu', ...
       'hMT_Slicing_CPU.cpp', ...
       'hTEMIm.cu');
