mexCPU(0, 'getAtomRadius.cpp', '../General_CPU_GPU', ...
       'hQuadrature.cpp',...
       'hMT_AtomicData_CPU.cpp',...
       'hPotential_CPU.cpp', ...
       'hGeneral_CPU.cpp',...
       'hMT_General_CPU.cpp',...
       'hMT_AtomTypes_CPU.cpp');
