MEX(0, 'get_fxg_CPU.cpp', '../General_CPU_GPU', ...
       'hQuadrature.cpp', ...
       'hGeneral_CPU.cpp', ...
       'hMT_AtomicData_CPU.cpp', ...
       'hPotential_CPU.cpp', ...
       'hMT_General_CPU.cpp', ...
       'hMT_AtomTypes_CPU.cpp', ...
       'hfxg_CPU.cpp');
