clc; clear all;
mexGPU(1, 'MULTEMMat.cu', '..\General\', 'hQuadrature.cpp', 'hAtomicdata.cpp'...
    , 'hPotentialCPU.cpp', 'hgeneralCPU.cpp', 'hSpecimenCPU.cpp', 'hMatlab2Cpp.cpp', 'hDetectorCPU.cpp'...
    , 'hgeneralGPU.cu', 'hPotentialGPU.cu', 'hAtomTypesGPU.cu', 'hMicroscopeEffectsGPU.cu'...
    , 'hIncidentWaveGPU.cu', 'hDetectorGPU.cu', 'hMulSliGPU.cu');