mexGPU(0, 'getTransmission.cu', '../General_CPU_GPU', ...
       'hGeneral_CPU.cpp', ...
       'hQuadrature.cpp', ...
       'hMT_AtomicData_CPU.cpp', ...
       'hPotential_CPU.cpp', ...
       'hMT_General_CPU.cpp', ...
       'hMT_Slicing_CPU.cpp', ...
       'hMT_Specimen_CPU.cpp', ...
       'hMT_AtomTypes_CPU.cpp', ...
       'hMT_General_GPU.cu', ...
       'hMT_AtomTypes_GPU.cu', ...
       'hMT_Potential_GPU.cu', ...
       'hMT_Transmission_GPU.cu');
